name: drinko_native
description: Aplikace pro měření pitného režimu
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dynamic_color: ^1.6.3
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
